#!/usr/bin/env node
const settings = require('./args')
const {cleanUp, createRelease, linkShared, runPostCommand} = require('./utils')

// @TODO: check for existence of file first
// Load deployment module
const deploy = require('./deploy-method-' + settings.deployMethod)

if (settings.debug) {
  console.log(settings)
}

// Use process.exit code to fail release and perform cleanup
process.on('exit', cleanUp);

(async () => {
  try {
    await createRelease()
    await deploy()
    await linkShared()
    await runPostCommand()
    // If we reach this line it was a successful release
    process.exit(0)
  } catch (error) {
    console.log(error)
    process.exit(1)
  }
})()